# Промты фонов под Veo / Gemini (13.0.2). Места и предметы — по реальным кадрам сцен (не по памяти о фильме). Запуск из корня dota-: python3 tools/bg_veo.py → фоны-промты-veo.txt
# Учтено по тестам «Ральфа» (4 модели): чёрные полосы сверху/снизу (letterbox), рамка-плёнка с перфорацией,
# дым из ниоткуда, бумажная лента, которая растёт, лишние предметы (телефон, пачка), плакаты с буквами,
# «3D-рендер» вместо кино, свет, который меняется (петля не сходится), горизонталь вместо 9:16.
# Поэтому: всё важное — по центру (горизонталь можно подрезать), не больше 2–3 движений и только «текстурных»
# (дым из одной точки, пар, рябь, мерцание, покачивание туда-обратно), свет постоянный, список «только эти предметы».
HEAD="Vertical 9:16 full-frame phone video; the picture fills the whole frame from edge to edge."
TAIL=("Keep the main objects in the center of the frame. Objects never grow, change shape, appear or disappear; "
      "the last frame looks the same as the first. Every object is at its real-life size and scale — nothing oversized. Photorealistic live-action footage with natural textures, not CGI, not a 3D render. "
      "Avoid: black bars, letterbox, frame borders, film strip, sprocket holes, split screen, text, letters, numbers, logos, watermarks, "
      "brand names, labels on bottles, posters, signs, people, faces, hands, extra objects, extra smoke, camera movement, zoom, cuts.")
# (заголовок, файл, место, камера, только эти предметы, движение, свет, настроение)
P=[
('ГЛАВНЫЙ «Волк с Уолл-стрит» · старый вариант','film-wolf',
 "the trading floor of a 1990s Long Island brokerage firm at night, the morning after a wild office party, nobody left.",
 "low angle at desk height, 24mm lens, looking down a long aisle of identical desks",
 "in the center foreground, one desk with a beige push-button office telephone, its handset lying off the hook; next to it a thick stack of hundred-dollar bills with a rubber band, one hundred-dollar bill rolled into a tight tube, a gold Rolex wristwatch, an empty champagne bottle lying on its side and a round glass fishbowl with one orange goldfish. Behind: rows of empty desks with boxy beige computer monitors glowing soft green with nothing on the screens; confetti and loose hundred-dollar bills scattered on the carpet.",
 "the goldfish hovers in place, gently waving its fins; the green glow of the monitors flickers very slightly.",
 "one brass desk lamp on the foreground desk (warm gold) and cold green from the monitors",
 "saturated gold against money-green; greedy, decadent and dirty, the hangover after a party of young millionaires."),
('Сцена «Марк Ханна объясняет новичку правила Уолл-стрит»','wolf-of-wall-street',
 "an expensive restaurant on the top floor of a tall downtown Manhattan tower at lunchtime, the dining room empty.",
 "eye level, 50mm lens, shallow focus, one table in the center",
 "a table with a white tablecloth, a small vase of yellow flowers, one full martini glass with a green olive on a pick and three empty martini glasses pushed aside, crystal water glasses, a small silver bowl of green olives and a tiny glass vial with a little silver spoon lying on the tablecloth. Behind it, more empty tables with white tablecloths and dark wooden chairs, and a wall of floor-to-ceiling windows with a hazy grey Manhattan skyline.",
 "thin haze drifts slowly over the skyline; soft glints shimmer on the crystal glasses.",
 "bright soft daylight from the windows",
 "cool bright daylight, white linen and steel-grey city; a smug mentor's cynical lunch lesson about money."),
('Сцена «Швейцарский банк: Ça dépend»','wolf-swiss-bank',
 "a private banker's office in Geneva on a sunny afternoon, polite, quiet and dangerous.",
 "eye level from the client's armchair, 35mm lens",
 "in the center, a polished dark wooden desk with a black leather folder, a small white espresso cup on a saucer, a tiny red Swiss desk flag with a white cross and a brass desk lamp. Behind the desk, a large backlit wall aquarium glowing turquoise with tropical fish and coral. On the right, a floor-to-ceiling window with Lake Geneva and the tall lake fountain shooting a white plume of water into the sky. Two dark leather armchairs, brown curtains.",
 "the tropical fish drift slowly in the aquarium; the fountain plume sways in the wind.",
 "warm afternoon sun from the window and the turquoise glow of the aquarium",
 "warm brown and turquoise; discreet old money, everything has a price."),
('ГЛАВНЫЙ «Клан Сопрано» · старый вариант','film-sopranos',
 "dawn in the backyard of a large suburban New Jersey house.",
 "high three-quarter angle, 35mm lens",
 "in the center, a rectangular swimming pool with calm blue-green water and two wild mallard ducks floating on it. At the pool edge: one white lounge chair with a white terry bathrobe draped over it, a rolled newspaper in a plastic bag lying on the paving, and a small side table with an unlit half-smoked cigar in a glass ashtray. Behind: the back of the house with sliding glass doors, one lit kitchen window and tall trees.",
 "the ducks float almost in place, leaving small ripples; thin morning mist drifts low over the water.",
 "soft overcast dawn and a warm glow from the kitchen window",
 "muted greens and beige; the quiet melancholy of a man who has everything and still panics."),
('Сцена «Тони на первом приёме у психотерапевта» (S01E01)','sopranos-s01e01',
 "a psychiatrist's office in 1999 in the evening, empty.",
 "eye level, 35mm lens",
 "dark wood-paneled walls with built-in bookshelves full of old books; in the center, two olive-green armchairs facing each other with a small low table between them holding a box of tissues and a cup of hot tea; on the wall, a small framed painting of two wild mallard ducks on a pond; a floor lamp with a fabric shade beside one chair; through a wide-open doorway, the dim waiting room with a bronze sculpture of a reclining female figure on a pedestal, clearly visible.",
 "dust specks drift slowly in the lamp light; a thin wisp of steam rises from the cup of tea.",
 "one warm floor lamp, the rest of the room in deep shadow",
 "dark walnut and olive green; heavy silence, a tough man's first confession."),
('Сцена «Тони у Мелфи: аттракционы и скука» (S06E09)','sopranos-s06e09',
 "the same psychiatrist's office years later, on a grey weekday afternoon, empty.",
 "eye level, 50mm lens",
 "a curved wall of dark wooden bookshelves; tall white vertical blinds glowing with flat daylight; in the center, a worn beige armchair; beside it a small glass table with a box of tissues, a glass carafe of water and a small open gift box with a pair of rolled socks inside; among the books on a shelf, a small vintage tin toy of a teacup carnival ride.",
 "the vertical blinds sway very slightly in the air from a vent; light ripples gently in the water carafe.",
 "flat cold daylight through the blinds",
 "cold grey daylight and dark wood; tired, bored, the same old conversation after years of therapy."),
('Сцена «Где моя арка?» (S01–S02)','sopranos-arc',
 "a young New Jersey gangster's apartment at night, late 1990s.",
 "low angle at couch height, 35mm lens",
 "in the center, a black leather couch with one black cushion; in front of it a low table with a heavy glass ashtray holding one lit cigarette, a gold wristwatch and a short stack of typed pages with no readable text. On the left, a large glowing home aquarium with a few tropical fish and one small shark — the main light of the room.",
 "the small shark keeps swimming slowly back and forth in the aquarium; one thin thread of smoke rises only from the tip of the cigarette.",
 "the cold blue glow of the aquarium, everything else in darkness",
 "blue glow in the dark; a small-time gangster who wants his life to have a movie arc."),
('Сцена «Ральф приходит к Тони» (S04E09)','sopranos-ralph',
 "the cramped back office of a New Jersey strip club at night, empty.",
 "slightly high angle over the desk, 28mm lens",
 "in the foreground, a cluttered desk with an old black office telephone, an old adding machine whose short paper tape lies still, a thick envelope stuffed with cash, loose papers, a glass of whiskey and a glass ashtray with one lit cigarette. Behind: dark green walls with small pink diamond-shaped lights, a pool table with green felt under a glowing stained-glass window made of amber, green and red squares, and steel beer kegs stacked in the corner. No posters.",
 "one thin thread of smoke rises only from the tip of the cigarette; the pink diamond lights pulse slowly.",
 "the glowing stained glass, the pink lights and one desk lamp",
 "sickly green and amber with pink spill; grief, guilt and dirty money."),
('ГЛАВНЫЙ «Американский психопат» · старый вариант','film-psycho',
 "a white marble bathroom in a 1987 Manhattan luxury apartment, early morning, empty.",
 "symmetrical frontal shot, 50mm lens",
 "a wide mirror above a white marble sink with a chrome faucet; on the counter, a perfectly straight row of skincare bottles and jars, an open jar of white face-mask cream, a folded white towel, a chrome razor, and one bone-white business card leaning against the mirror. The mirror reflects only the white wall behind.",
 "a single water drop forms on the faucet and falls into the sink, again and again; a faint wisp of steam rises from the sink.",
 "cold white light from frosted glass fixtures",
 "icy white and chrome; sterile perfection hiding a cold emptiness."),
('Сцена «Патрик Бейтман приходит в офис»','american-psycho',
 "a 1987 Wall Street executive office in the morning, empty.",
 "three-quarter view from the doorway, 35mm lens",
 "grey-green walls with two small framed prints; in the center, a polished mahogany desk with a black leather office chair; on the desk, a sleek black telephone, an open leather appointment book, a silver portable cassette player with headphones and a glass of sparkling water; a gym bag with a white towel on a guest chair. Behind, tall windows with half-closed metal venetian blinds and Manhattan skyscrapers behind them.",
 "bubbles rise in the sparkling water; haze drifts slowly between the skyscrapers behind the blinds.",
 "cold morning daylight through the blinds",
 "cold grey-green and mahogany; sterile, arrogant 1980s yuppie morning."),
('Сцена «Визитки: чья круче»','american-psycho-cards',
 "a 1987 Wall Street boardroom, empty.",
 "low grazing angle across the table, 100mm macro lens, very shallow focus",
 "on a dark polished wooden table, five business cards laid in a neat row, each a slightly different shade of white (bone, eggshell, ivory), with tiny raised black lettering too small to read; beside them, a crystal tumbler of whiskey with ice. Behind, out of focus, dark wood paneling and venetian blinds.",
 "water droplets slide down the cold tumbler; a soft highlight glides slowly along the edge of the cards and back.",
 "soft daylight through the blinds in a dim room",
 "dark wood with creamy whites; petty envy, a man sweating over someone else's business card."),
('ГЛАВНЫЙ «Таксист» · старый вариант','film-taxi',
 "a wet 1970s New York side street at night, empty.",
 "low angle from the curb, 28mm lens",
 "in the center, a yellow 1970s Checker taxi cab with a checkered stripe parked at the curb with its roof light on; in front of it, a round manhole cover in the street. Behind, out of focus, shop windows glowing red and blue.",
 "white steam billows slowly only from the manhole and drifts past the taxi; neon reflections shimmer in the puddles.",
 "orange street lamps and red and blue neon reflected on the wet asphalt",
 "gritty 1970s, sodium orange; a lonely city at night."),
('Сцена «Одинокий человек Бога»','taxi-driver-lonely',
 "inside a 1970s New York yellow taxi cab at night, seen from the empty back seat.",
 "from the back seat, 28mm lens, looking forward through the windshield",
 "the scratched plexiglass partition, the empty driver's seat, an open diary with blurred handwriting on the front passenger seat, an old mechanical taxi meter on the dashboard with no readable numbers and a crumpled pack of cigarettes next to it; through the wet windshield, a blurry night street glowing with soft out-of-focus red, green and yellow neon lights.",
 "blurry neon lights slide slowly across the wet windshield; raindrops trickle down the glass.",
 "only the neon from outside",
 "red and green neon in darkness; insomnia, a lonely night shift in a filthy city."),
('Сцена «Трэвис зовёт Бетси на кофе»','taxi-driver-betsy',
 "a 1972 presidential campaign headquarters in New York on a sunny day, empty.",
 "eye level, 35mm lens",
 "red-white-and-blue paper bunting hanging along the walls; desks with typewriters, telephones and piles of leaflets; on the front desk, a small vase of yellow flowers, a paper cup of coffee, a slice of pie on a paper plate and a small desk fan; red carpet; big windows with daylight and green trees outside; flags with stars and stripes, no posters, no text.",
 "the bunting ripples gently in the breeze of a small desk fan; the desk fan blades turn.",
 "bright warm daylight from the windows",
 "warm red, white and blue, bright 1970s optimism; an awkward, hopeful invitation to a date."),
('ГЛАВНЫЙ «Бункер» · старый вариант','film-bunker',
 "a narrow underground concrete corridor of a Berlin bunker, April 1945, empty.",
 "one-point perspective down the corridor, 24mm lens, chest height",
 "bare light bulbs hanging from cables along the ceiling, a wooden chair and a small table with an old field telephone in the foreground, a heavy steel door half open on the side. No flags, symbols or insignia.",
 "the bulbs flicker and dim for a moment as distant explosions shake the bunker, then come back; fine dust drifts down from the ceiling.",
 "only the dim yellow bulbs",
 "grey-green concrete and sickly yellow; claustrophobic, the end is near."),
('Сцена «Приказ Штайнера»','downfall-bunker',
 "a small grey-green concrete conference room in a bunker, 1945, empty.",
 "high angle looking down at the table, 35mm lens",
 "a large old map of Europe on the wall; in the center, a big table covered with a paper map of Berlin with blue and red pencil marks; a pair of round wire-rimmed glasses lying on the map; a red-and-blue pencil thrown down across it; a green-shaded lamp hanging low above the table. No flags, symbols or insignia, no readable text.",
 "the hanging lamp sways gently back and forth, its pool of light sliding over the map and back; fine dust floats in the light.",
 "only the hanging lamp",
 "grey-green concrete and pale light; the seconds after a furious outburst, the war is lost."),
('ГЛАВНЫЙ «Титаник» · старый вариант','film-titanic',
 "the bow of a large 1912 ocean liner at sunset, empty deck.",
 "centered low angle looking forward to the tip of the bow, 24mm lens",
 "white railings converging to the point of the bow, wooden deck planks, a coiled rope and an anchor winch. Beyond the bow: calm open ocean and a golden-pink sunset sky.",
 "the sea glitters and slides past the bow as the ship moves forward; clouds drift slowly.",
 "warm low sun",
 "warm golden romance, epic and calm; the feeling of flying."),
('Сцена «Джек сажает Роуз в шлюпку»','titanic-boat',
 "the boat deck of a large 1912 ocean liner at night during the sinking, empty.",
 "eye level along the deck, 35mm lens",
 "white-painted steel walls with round brass deck lamps; in the center, an empty wooden lifeboat hanging from two steel davits by ropes beside the railing, the black ocean far below; a dropped white fur stole on the deck; a white canvas life jacket hanging on the railing; the deck tilts slightly toward the bow.",
 "the empty lifeboat sways slightly on its ropes; the deck lamps flicker as the power fails.",
 "the round deck lamps, warm against the black night",
 "freezing blue night with warm failing lights; a tragic goodbye."),
('ГЛАВНЫЙ «Во все тяжкие» · старый вариант','film-bb',
 "the New Mexico desert at golden hour.",
 "low wide angle, 24mm lens",
 "in the center, an old 1980s white motorhome with faded brown stripes parked on the red sand, its side door open; a black pork-pie hat rests on the motorhome's metal step; a green gas mask lies on the sand nearby. Behind, red mesas under a huge sky.",
 "heat haze shimmers above the sand; small swirls of dust blow low across the ground.",
 "low warm sun",
 "sun-baked yellow-amber, high contrast; an ominous calm."),
('Сцена «Учитель химии едет на рейд» (S01E01)','breaking-bad-pilot',
 "inside a car on a DEA stakeout on a sunny Albuquerque suburban street, nobody inside.",
 "from the back seat between the front seats, 28mm lens, looking through the windshield",
 "on the dashboard, a pair of aviator sunglasses and a folded paper map; on the passenger seat, a black tactical vest with a gold badge patch and no text; a police radio with a handset on a coiled cord. Through the windshield: a quiet street of beige stucco houses; the last house on the right is a one-story house painted sage green, and next to it a two-story house with an upstairs window wide open and a curtain hanging out of it; and blue mountains far away.",
 "heat haze shimmers above the asphalt; the curtain flutters out of the open upstairs window; the radio's small red light blinks.",
 "harsh midday sun",
 "bleached sun with a yellow-green tint; a boring stakeout that is about to change a teacher's life."),
('Сцена «Уолт приходит к Гасу» (S02E11)','breaking-bad-gus',
 "an empty fast-food fried chicken restaurant in Albuquerque at night, closed.",
 "eye level, 28mm lens",
 "walls painted blue on the lower half and white above, red vinyl booths, light wooden tables and chairs, white floor tiles with small blue diamond inlays, ceiling fans, dark windows onto an empty parking lot. On the nearest table, a red plastic tray with a paper cup of cola with a straw and an untouched basket of fried chicken. No logos and no signs.",
 "the ceiling fans turn slowly; condensation drops slide down the cold soda cup.",
 "bright flat fluorescent ceiling light",
 "flat bright fluorescent; too clean, too polite, quietly menacing."),
('Сцена «Я тот, кто стучит» (S04E06 · S04E11)','breaking-bad-knocks',
 "a crawl space under a suburban house, seen from above.",
 "looking straight down through an open square wooden floor hatch, 24mm lens",
 "through the hatch: a dirt floor between wooden floor joists and pink insulation, almost empty — only two small bundles of cash wrapped in clear plastic left among torn empty plastic wrappers where a huge pile of money used to be; one bare light bulb hanging on a cord.",
 "the bulb sways slowly on its cord and back, the shadows of the joists swing across the empty dirt; dust floats in the light.",
 "only the bare bulb",
 "harsh yellow and deep black; the money is gone — despair turning into mad laughter."),
('ГЛАВНЫЙ «Павел Дуров» · старый вариант','film-durov',
 "a minimalist dark office high above a glittering city at night, empty.",
 "centered shot toward a floor-to-ceiling window, 35mm lens",
 "in the foreground, a plain black desk with a single folded white paper airplane and a closed laptop. Behind the glass, the glittering night skyline of a big modern city.",
 "the city lights twinkle; tiny car lights stream along the highways far below.",
 "city lights and a faint cool desk light",
 "black, white and electric blue; minimal, calm freedom."),
('Сцена «Такер Карлсон · 2024»','durov-tucker',
 "a dark, elegant interview room, empty, just before filming.",
 "wide symmetrical shot, 35mm lens",
 "a wall of vertical dark wooden slats; dark marble shelves with a few white sculptural objects and a small white classical bust; in the center, two black armchairs facing each other with a small round black table between them holding two glasses of water and a single folded white paper airplane; a window with light wooden blinds; two professional video cameras on tripods at the left and right edges, pointed at the chairs.",
 "the small red recording light on each camera blinks; light ripples faintly in the water glasses.",
 "warm low lamps and soft daylight through the blinds",
 "dark wood, black and white marble; serious, a big conversation is about to start."),
('ГЛАВНЫЙ «Clavicular» (сам стример, не студия) · старый вариант','film-clavicular',
 "the balcony of a Miami high-rise apartment at night, empty — the home of a young looksmaxxing streamer who is always live.",
 "eye level, 35mm lens",
 "a glass balcony railing; a white lounge chair with a black knit polo shirt draped over it and black sunglasses hooked on its collar; on a small glass table, a smartphone on a mini tripod with a small ring light, its screen glowing neon green with floating chat bubbles and hearts and no letters, and a silver wristwatch; a full-length mirror leaning against the wall, reflecting only city lights. Behind: the Miami skyline at night, tall palm trees and pink and purple neon reflected in the bay.",
 "chat bubbles and hearts float up the phone screen; the palm leaves sway slightly in the warm wind.",
 "the neon-green glow of the phone, the ring light and pink-purple city neon",
 "neon green and hot pink; a 20-year-old obsessed with his looks, Miami nights, always on stream."),
('Сцена «Подкаст Impaulsive» (студия)','clavicular-impaulsive',
 "a big podcast studio right after recording, empty.",
 "wide shot from a high corner, 24mm lens",
 "two large cream-colored couches facing each other; between them a low wooden coffee table with paper snack trays, two plain unlabeled plastic bottles of blue sports drink and a smartphone lying face up with green message bubbles on its screen; behind, a wall of warm wooden planks with shelves of small gold trophies; black podcast microphones on boom arms in front of the couches; a video camera on a tripod at the edge of the frame; studio spotlights on the ceiling. No boxing ring, no ropes, no logos, no text.",
 "condensation drops slide down the cold bottles on the table; a tiny red recording light blinks on a camera at the edge of the frame.",
 "warm studio lights",
 "warm wood, cream and red-white-blue; loud, confident, a little bit show-off."),
('Сцена «Clavicular · 18+» (VIP-ложа клуба в Майами после закрытия)','clavicular-18',
 "a VIP booth of a Miami nightclub at 4 a.m. after closing, empty, no people.",
 "eye level from the low table, 28mm lens, the booth fills the center",
 "a curved black velvet booth; on the low black table in front of it: a silver ice bucket with a dark unlabeled champagne bottle, two half-empty champagne glasses, an open orange pharmacy pill bottle with a few small blue diamond-shaped pills spilled out, and a smartphone lying face up, its screen glowing neon green with chat bubbles and no letters; behind the booth, a dark wall with thin pink and red neon light strips (no words) and a mirrored disco ball hanging from the ceiling; light haze in the air.",
 "the disco ball turns slowly, small light spots glide across the walls; chat bubbles float up the phone screen; a thin haze drifts.",
 "pink and red neon, the green phone glow, spots from the disco ball",
 "hot pink, red and neon green in darkness; the after-party, no-filter talk about sex, pills, dopamine and money."),

]
# 13.1: главные фоны — ВЕСЬ фильм / сериал целиком (главные символы в одном логичном месте), у интервью — сам человек. Старые варианты остаются ниже.
PH=[
('ГЛАВНЫЙ «Волк с Уолл-стрит» — весь фильм','film-wolf-b',
 "the trading floor of a 1990s Long Island brokerage firm at night, the morning after a wild office party, nobody left.",
 "low angle across the nearest desk, 28mm lens, a long aisle of desks behind",
 "on the nearest desk, in the center: thick bricks of hundred-dollar bills in paper bands, a beige office telephone with the handset off the hook, a tipped-over pharmacy pill bottle with a few round white pills spilled out, an unlabeled champagne bottle with a half-full champagne glass, a small white toy model of a 1980s Lamborghini Countach and a round fishbowl with one orange goldfish. Behind: rows of empty desks with boxy beige monitors glowing green, confetti and loose bills on the carpet.",
 "the goldfish hovers in place waving its fins; bubbles rise in a glass of champagne.",
 "one warm brass desk lamp and cold green monitor glow",
 "gold and money-green; greed, excess, drugs and endless partying on other people's money."),
('ГЛАВНЫЙ «Клан Сопрано» — весь сериал','film-sopranos-b',
 "the big kitchen of a New Jersey mob boss's suburban house at 3 a.m., empty.",
 "eye level from the kitchen island, 35mm lens",
 "the door of a large refrigerator stands open, its light the main light in the dark kitchen; on the island in front of it: a white plate with thin slices of capicola, a glass of whiskey, a cigar resting in a heavy glass ashtray and a foil tray of baked ziti; a rolled newspaper in a plastic bag on the counter; a white terry bathrobe hangs over a bar stool; through the sliding glass door, a backyard swimming pool lit from below with two wild ducks floating on it.",
 "one thin thread of smoke rises only from the tip of the cigar; the ducks float almost in place, leaving small ripples on the lit pool.",
 "cold white light from the open refrigerator and the turquoise glow of the pool",
 "cold fridge light and darkness; family, money, food, guilt and panic attacks — a mob boss who can't sleep."),
('ГЛАВНЫЙ «Американский психопат» — весь фильм','film-psycho-b',
 "a minimalist white 1987 Manhattan luxury apartment at night, empty.",
 "symmetrical wide shot, 28mm lens",
 "the white floor covered with neatly spread newspapers with blurred unreadable print; in the center, a transparent plastic raincoat hanging on a chrome coat stand; a fire axe leaning against a white leather sofa; on a glass coffee table, a row of bone-white business cards, an open jar of white face-mask cream; a high-end silver stereo system with glowing level meters; a big window onto the Manhattan skyline at night.",
 "the green level meters on the stereo bounce to music; a corner of a newspaper flutters slightly in the air from a vent.",
 "cold white ceiling light and the blue night city",
 "sterile white perfection with something horribly wrong; a polite yuppie who is a monster inside."),
('ГЛАВНЫЙ «Таксист» — весь фильм','film-taxi-b',
 "a tiny cheap rented room in 1970s New York at night, empty.",
 "eye level, 28mm lens",
 "a small cracked mirror on a dingy yellow wall above an old dresser; on the dresser, all at real size: a black revolver lying flat, only as long as the open diary next to it, aviator sunglasses, an open diary with blurred handwriting, a saucer with a slice of white bread, a small round red-white-and-blue button with no text, and a bottle of brandy with no label; an olive-green army field jacket hangs beside the mirror; an old portable TV with grey static on the floor; through the window, a wet street with red neon and a yellow taxi parked below in a cloud of steam.",
 "the TV static flickers; steam drifts past the taxi outside the window.",
 "one bare bulb, the TV glow and red neon from the street",
 "dirty yellow and red; a lonely insomniac talking to his mirror, violence brewing."),
('ГЛАВНЫЙ «Бункер» — весь фильм','film-bunker-b',
 "the ruined center of Berlin at dusk in April 1945, seen from the steps of an underground bunker exit, empty.",
 "low angle from the bunker steps, 24mm lens",
 "in the foreground on a wooden crate, a paper map of Berlin with red and blue pencil arrows, a pair of round wire-rimmed glasses and a broken pencil; behind, the burned shells of grand buildings, a damaged domed government building and broken stone columns under a red smoky sky. No flags, symbols or insignia, no text.",
 "thick smoke drifts slowly across the ruins; orange embers float in the air.",
 "red-orange fire glow under a dark smoky sky",
 "red, black and ash grey; the end of an empire, everything is lost."),
('ГЛАВНЫЙ «Титаник» — весь фильм','film-titanic-b',
 "the bow of a huge 1912 ocean liner at dusk on a calm sea, empty deck. The sun has just set: the sky is deep orange and pink at the horizon and dark blue above; it is NOT daytime.",
 "chest height, about four meters behind the tip of the bow, 35mm lens, looking forward to the tip of the bow",
 "white railings converging to the point of the bow; old wooden deck planks; at the very tip of the bow, lying on the planks, a small delicate necklace with a heart-shaped blue gemstone pendant at real jewelry size — the heart is no bigger than a walnut and the chain is thin, so from this distance it is a small sparkle on the deck, not a big object; a white canvas life jacket lying beside the railing; far ahead on the horizon, a tall pale iceberg in thin mist.",
 "the small blue gem catches the last light and sparkles softly; the sea slides past the bow; thin mist drifts around the distant iceberg.",
 "the last warm orange glow of the sunset and the first cold blue of night",
 "golden-orange romance turning into icy blue doom; love and catastrophe."),
('ГЛАВНЫЙ «Во все тяжкие» — весь сериал','film-bb-b',
 "the New Mexico desert at golden hour, nobody around.",
 "low wide angle, 24mm lens",
 "in the center, an old 1980s white motorhome with faded brown stripes, its side door open, a yellow hazmat suit hanging from the door; a black pork-pie hat resting on the metal step; a black gas mask on the sand; a blue plastic barrel half buried in the sand with bundles of cash showing at the top; a pair of khaki pants caught on a desert shrub; a few sky-blue glass-like crystals glinting on the step. Red mesas behind under a huge sky.",
 "the khaki pants flap on the shrub in the hot wind; heat haze shimmers above the sand.",
 "low warm sun",
 "sun-baked yellow and crystal blue; a chemistry teacher who became a kingpin."),
('ГЛАВНЫЙ «Павел Дуров» — сам человек','film-durov-b',
 "a minimalist all-black room at night by a huge window over a private airfield, empty.",
 "eye level, 35mm lens",
 "a plain black desk with a closed black laptop, a folded black T-shirt and a single white paper airplane; on the wide windowsill, a small pile of paper airplanes folded from orange banknotes; outside, a white private jet on the wet tarmac with its stairs down and blue runway lights beyond.",
 "the jet's red beacon light blinks; reflections of the runway lights shimmer on the wet tarmac.",
 "cool blue night light and one faint desk lamp",
 "black, white and electric blue; freedom, minimalism, always on the move."),
('ГЛАВНЫЙ «Clavicular» — сам человек (лукмаксинг)','film-clavicular-b',
 "the bathroom of a Miami high-rise apartment at night, turned into a looksmaxxing station, empty.",
 "eye level facing the vanity, 35mm lens",
 "a big mirror with bright bulbs around it, reflecting only the dark room; on the white marble counter: a small steel hammer, a microneedling derma roller, a metal tray with a few small glass vials and capped syringes, a roll of mouth tape, a silicone jaw exerciser, a glass bowl filled with ice cubes resting still on the counter, a row of skincare bottles, and a smartphone on a tripod with a ring light, its screen glowing neon green with chat bubbles and no letters; a black knit polo shirt with black sunglasses hooked on its collar hangs on a hook; a small window shows Miami towers, palm trees and pink-purple neon.",
 "chat bubbles float up the phone screen; the palm trees outside the small window sway slightly. The bowl of ice stands perfectly still: no dripping, no falling water, no rain anywhere.",
 "bright vanity bulbs, the neon-green phone glow and pink city neon",
 "clinical white, neon green and hot pink; extreme self-improvement, obsession with the mirror, always on stream."),
]

# 13.5: немецкие сцены (дубляж). У «Ланча» и «Я — опасность» сцена та же, что у английских, — фон общий (скопирую файл).
# Главные фоны немецких фильмов — те же, что у английских (Волк, Сопрано, Во все тяжкие, Титаник), отдельно генерить не надо.
PDE=[
('DE «Первое свидание с Наоми» (Волк)','wolf-naomi-de',
 "a dim, cozy Italian restaurant in early 1990s New York at night, the table for two empty.",
 "eye level across the table, 50mm lens, shallow focus",
 "a small round table with a white tablecloth; a short table lamp with a cream fabric shade glowing warm; a low vase of pink roses; one cocktail glass with a white bendy straw in it and a glass of red wine; a folded white napkin. Behind, out of focus: dark red brick walls, more little glowing table lamps and dark wooden chairs.",
 "the little lamps glow steadily while candle-like reflections shimmer softly in the glasses; a thin ribbon of condensation slides down the cocktail glass.",
 "the warm table lamps, everything else in soft darkness",
 "warm amber and dark red; a married man on a first date that is obviously not \"just friends\"."),
('DE «Тони, Мелфи и Махаффи» (Сопрано S01E01)','sopranos-mahaffey-de',
 "the grass lawn of a quiet New Jersey corporate office park on a grey morning, empty.",
 "low angle from the grass, 28mm lens",
 "a black 1999 luxury sedan stopped crooked on the lawn with the driver's door open; on the asphalt path in front of it, two spilled paper coffee cups and a crushed cardboard cup tray in a small puddle of coffee; one brown leather office shoe lying alone on the grass. Behind: a low office building with dark glass and big weeping willow trees.",
 "thin steam rises from the spilled coffee; the long willow branches sway gently in the wind.",
 "flat grey overcast morning light",
 "muted green and grey; a pleasant suburban morning that just turned into a beating."),
('DE «Хасиды нанимают Тони» (Сопрано S01E03)','sopranos-hasid-de',
 "the sidewalk in front of a small Italian pork store in New Jersey on a sunny summer day, empty.",
 "eye level from the curb, 35mm lens",
 "two small café tables with red-and-white checkered tablecloths; on one, two white espresso cups on saucers and a sugar dispenser; a black wide-brimmed felt hat left on one chair; behind, the shop window with hanging salamis and a cartoon pig figure in the window with no letters; a striped awning above. No text, no signs with words.",
 "the edge of a checkered tablecloth flutters in the breeze; a thin wisp of steam rises from one espresso cup.",
 "bright summer daylight",
 "warm red-white checks and sunlight; a polite business deal between very different men."),
('DE «Фил решает» (Сопрано S06E20)','sopranos-phil-de',
 "a small old Brooklyn café on a winter afternoon, empty.",
 "eye level, 50mm lens, shallow focus on the front table",
 "a small round marble table with a white espresso cup on a saucer and a little spoon resting in it, a glass of water and a folded white pocket square; behind, dark wooden walls with old framed photos, bentwood chairs and big windows with glowing lace curtains.",
 "a thin wisp of steam rises from the espresso; the lace curtains sway very slightly.",
 "pale wintry daylight through the lace curtains, dark interior",
 "brown and pale cream; quiet coffee, cold decision — the end of a war is ordered here."),
('DE «Ich bin die Gefahr» (Во все тяжкие S04E06)','bb-knocks-de',
 "the dark front hallway of a suburban Albuquerque house at night, seen from inside, empty.",
 "eye level facing the front door, 35mm lens",
 "a closed wooden front door with a small frosted glass window glowing yellow from the porch light outside; a brass door chain hanging loose; on a small side table by the door, a black pork-pie hat and a pair of glasses; a family photo frame turned face down.",
 "the porch light behind the frosted glass flickers slightly; a moth's shadow flutters on the glass.",
 "only the yellow porch light through the frosted glass",
 "black and sickly yellow; the knock at the door — and the one who knocks is him."),
('DE «Майк и ноутбук Гаса» (Во все тяжкие S05E01)','bb-mike-de',
 "the empty New Mexico desert at golden hour, nobody around.",
 "low angle from the dirt road, 28mm lens",
 "a dusty silver 1990s sedan parked on a dirt track with the driver's door open; on its hood: a ring of car keys and a black revolver; a closed black laptop lying in the dust in front of the car. Behind, flat desert with dry grass and blue mountains under a huge sky.",
 "dry grass sways in the hot wind; heat haze shimmers above the road; thin dust blows low across the ground.",
 "low warm golden sun",
 "dusty gold and black; an old fixer who is done with these amateurs — and evidence that can sink them all."),
('DE «Эндрюс: корабль утонет» (Титаник)','titanic-andrews-de',
 "the chart room of a 1912 ocean liner at night, empty.",
 "high angle over the table, 35mm lens",
 "a large wooden table covered with a big blue ship blueprint of the liner seen from the side, its compartments drawn in white lines; a brass desk lamp; a gold pocket watch lying open on the blueprint; a pencil and a brass ruler; behind, dark wood paneling and a round porthole showing black night sea.",
 "the brass lamp sways very slightly back and forth as the ship lists, its pool of light sliding over the blueprint and back; the pocket watch's second hand ticks.",
 "only the warm brass lamp",
 "deep blue and warm brass; calm numbers that mean death — a mathematical certainty."),
('DE «Мать и корсет» (Титаник)','titanic-mother-de',
 "a luxurious first-class stateroom of a 1912 ocean liner in the evening, empty.",
 "eye level, 50mm lens, shallow focus",
 "a dressing table with a big oval mirror reflecting only the room; on it, a pearl necklace, a silver hairbrush and a vase of yellow lilies; a white corset with long loose laces hanging over a carved wooden screen; heavy dark-red velvet curtains; warm wall sconces with small shades.",
 "the loose corset laces sway slightly; the velvet curtain moves very gently.",
 "warm golden wall sconces",
 "gold, cream and blood red; luxury that feels like a cage."),
]

def prompt(pl,cam,obj,mv,li,look):
    return (f"{HEAD} Place: {pl} Camera: {cam}, locked-off, does not move. Only these objects: {obj} "
            f"Moves (only this): {mv} Everything else stays perfectly still. Light: {li}, constant the whole time. "
            f"Mood: {look} {TAIL}")
if __name__=='__main__':
    o=['ФОНЫ — ПРОМТЫ ДЛЯ VEO / GEMINI','',
       'Настройки: 9:16, 8 с. Каждый блок — один промт, копируй целиком.',
       'Если всё равно вышла горизонталь — не страшно: всё важное в промтах по центру, я подрежу под телефон.',
       'Если «I can\'t generate that video» — убери из промта одну «острую» деталь (шприцы, молоток, топор, револьвер, таблетки, свёрнутую купюру, сигарету) и прогони ещё раз.',
       'Вертикаль: в приложении Gemini видео почти всегда горизонтальное — вертикаль 9:16 выбирается в Google Flow (labs.google/flow) или AI Studio. Горизонталь тоже годится: в «Коллекции» она показывается целиком.',
       'Если модель добавила лишнее (ринг, логотип на бутылке, людей) — перегенерируй тот же промт, не дописывай; чем короче список предметов, тем точнее.','','']
    o+=['##### НОВЫЕ ГЛАВНЫЕ ФОНЫ — ВЕСЬ ФИЛЬМ / СЕРИАЛ, У ИНТЕРВЬЮ — САМ ЧЕЛОВЕК (13.1) #####','','']
    for h,f,*x in PH:o+=[f'=== {h} → файл {f}.mp4 ===','',prompt(*x),'','']
    o+=['##### ФОНЫ СЦЕН и прежние варианты главных #####','','']
    for h,f,*x in P:o+=[f'=== {h} → файл {f}.mp4 ===','',prompt(*x),'','']
    o+=['##### НЕМЕЦКИЕ СЦЕНЫ (13.5) — «Ланч» и «Я — опасность» берут фон английских сцен #####','','']
    for h,f,*x in PDE:o+=[f'=== {h} → файл {f}.mp4 ===','',prompt(*x),'','']
    open('фоны-промты-veo.txt','w').write('\n'.join(o));print(len(P))
    # чистый файл: только актуальное — новые главные (весь фильм / человек) + фоны сцен, без старых главных
    c=['ФОНЫ — АКТУАЛЬНЫЕ ПРОМТЫ (без старых вариантов)','',o[2],o[3],o[4],o[5],o[6],'','','##### ГЛАВНЫЕ ФОНЫ — ВЕСЬ ФИЛЬМ / СЕРИАЛ, У ИНТЕРВЬЮ — САМ ЧЕЛОВЕК #####','','']
    for h,f,*x in PH:c+=[f'=== {h} → файл {f}.mp4 ===','',prompt(*x),'','']
    c+=['##### ФОНЫ СЦЕН #####','','']
    for h,f,*x in P:
        if not f.startswith('film-'):c+=[f'=== {h} → файл {f}.mp4 ===','',prompt(*x),'','']
    c+=['##### НЕМЕЦКИЕ СЦЕНЫ (13.5) #####','','']
    for h,f,*x in PDE:c+=[f'=== {h} → файл {f}.mp4 ===','',prompt(*x),'','']
    open('фоны-промты-АКТУАЛЬНЫЕ.txt','w').write('\n'.join(c))
