# Промты фонов под Veo / Gemini (13.0.2). Места и предметы — по реальным кадрам сцен (не по памяти о фильме). Запуск из корня dota-: python3 tools/bg_veo.py → фоны-промты-veo.txt
# Учтено по тестам «Ральфа» (4 модели): чёрные полосы сверху/снизу (letterbox), рамка-плёнка с перфорацией,
# дым из ниоткуда, бумажная лента, которая растёт, лишние предметы (телефон, пачка), плакаты с буквами,
# «3D-рендер» вместо кино, свет, который меняется (петля не сходится), горизонталь вместо 9:16.
# Поэтому: всё важное — по центру (горизонталь можно подрезать), не больше 2–3 движений и только «текстурных»
# (дым из одной точки, пар, рябь, мерцание, покачивание туда-обратно), свет постоянный, список «только эти предметы».
HEAD="Vertical 9:16 full-frame phone video; the picture fills the whole frame from edge to edge."
TAIL=("Keep the main objects in the center of the frame. Objects never grow, change shape, appear or disappear; "
      "the last frame looks the same as the first. Photorealistic live-action footage with natural textures, not CGI, not a 3D render. "
      "Avoid: black bars, letterbox, frame borders, film strip, sprocket holes, split screen, text, letters, numbers, logos, watermarks, "
      "posters, signs, people, faces, hands, extra objects, extra smoke, camera movement, zoom, cuts.")
# (заголовок, файл, место, камера, только эти предметы, движение, свет, настроение)
P=[
('ГЛАВНЫЙ «Волк с Уолл-стрит»','film-wolf',
 "the trading floor of a 1990s Long Island brokerage firm at night, the morning after a wild office party, nobody left.",
 "low angle at desk height, 24mm lens, looking down a long aisle of identical desks",
 "in the center foreground, one desk with a beige push-button office telephone, its handset lying off the hook; next to it a thick stack of hundred-dollar bills with a rubber band, one hundred-dollar bill rolled into a tight tube, a gold Rolex wristwatch, an empty champagne bottle lying on its side and a round glass fishbowl with one orange goldfish. Behind: rows of empty desks with boxy beige computer monitors glowing soft green with nothing on the screens; confetti and loose hundred-dollar bills scattered on the carpet.",
 "the goldfish hovers in place, gently waving its fins; the green glow of the monitors flickers very slightly.",
 "one brass desk lamp on the foreground desk (warm gold) and cold green from the monitors",
 "saturated gold against money-green; greedy, decadent and dirty, the hangover after a party of young millionaires."),
('Сцена «Марк Ханна объясняет новичку правила Уолл-стрит»','wolf-of-wall-street',
 "an expensive restaurant on a very high floor of a Manhattan skyscraper at lunchtime, the dining room empty.",
 "eye level, 50mm lens, shallow focus, one table in the center",
 "a table with a white tablecloth, a small vase of yellow flowers, two martini glasses with a green olive on a pick, crystal water glasses and a small silver bowl of green olives. Behind it, more empty tables with white tablecloths and dark wooden chairs, and a wall of floor-to-ceiling windows with a hazy grey Manhattan skyline.",
 "thin haze drifts slowly over the skyline; soft glints shimmer on the crystal glasses.",
 "bright soft daylight from the windows",
 "cool bright daylight, white linen and steel-grey city; a smug mentor's cynical lunch lesson about money."),
('Сцена «Швейцарский банк: Ça dépend»','wolf-swiss-bank',
 "a private banker's office in Geneva on a sunny afternoon, polite, quiet and dangerous.",
 "eye level from the client's armchair, 35mm lens",
 "in the center, a polished dark wooden desk with a black leather folder, a small white espresso cup on a saucer and a brass desk lamp. Behind the desk, a large backlit wall aquarium glowing turquoise with tropical fish and coral. On the right, a floor-to-ceiling window with Lake Geneva and the tall lake fountain shooting a white plume of water into the sky. Two dark leather armchairs, brown curtains.",
 "the tropical fish drift slowly in the aquarium; the fountain plume sways in the wind.",
 "warm afternoon sun from the window and the turquoise glow of the aquarium",
 "warm brown and turquoise; discreet old money, everything has a price."),
('ГЛАВНЫЙ «Клан Сопрано»','film-sopranos',
 "dawn in the backyard of a large suburban New Jersey house.",
 "high three-quarter angle, 35mm lens",
 "in the center, a rectangular swimming pool with calm blue-green water and two wild mallard ducks floating on it. At the pool edge: one white lounge chair with a white terry bathrobe draped over it, a rolled newspaper in a plastic bag lying on the paving, and a small side table with an unlit half-smoked cigar in a glass ashtray. Behind: the back of the house with sliding glass doors, one lit kitchen window and tall trees.",
 "the ducks float almost in place, leaving small ripples; thin morning mist drifts low over the water.",
 "soft overcast dawn and a warm glow from the kitchen window",
 "muted greens and beige; the quiet melancholy of a man who has everything and still panics."),
('Сцена «Тони на первом приёме у психотерапевта» (S01E01)','sopranos-s01e01',
 "a psychiatrist's office in 1999 in the evening, empty.",
 "eye level, 35mm lens",
 "dark wood-paneled walls with built-in bookshelves full of old books; in the center, two olive-green armchairs facing each other with a small low table between them holding a box of tissues; a floor lamp with a fabric shade beside one chair; a doorway into a dim waiting room.",
 "dust specks drift slowly in the lamp light; the lamp glow barely flickers.",
 "one warm floor lamp, the rest of the room in deep shadow",
 "dark walnut and olive green; heavy silence, a tough man's first confession."),
('Сцена «Тони у Мелфи: аттракционы и скука» (S06E09)','sopranos-s06e09',
 "the same psychiatrist's office years later, on a grey weekday afternoon, empty.",
 "eye level, 50mm lens",
 "a curved wall of dark wooden bookshelves; tall white vertical blinds glowing with flat daylight; in the center, a worn beige armchair; beside it a small glass table with a box of tissues and a glass carafe of water.",
 "the vertical blinds sway very slightly in the air from a vent; light ripples gently in the water carafe.",
 "flat cold daylight through the blinds",
 "cold grey daylight and dark wood; tired, bored, the same old conversation after years of therapy."),
('Сцена «Где моя арка?» (S01–S02)','sopranos-arc',
 "a young New Jersey gangster's apartment at night, late 1990s.",
 "low angle at couch height, 35mm lens",
 "in the center, a black leather couch with one black cushion; in front of it a low table with a heavy glass ashtray holding one lit cigarette, a gold wristwatch and a short stack of typed pages with no readable text. On the left, a large glowing home aquarium with a few tropical fish — the main light of the room.",
 "the fish drift slowly in the aquarium; one thin thread of smoke rises only from the tip of the cigarette.",
 "the cold blue glow of the aquarium, everything else in darkness",
 "blue glow in the dark; a small-time gangster who wants his life to have a movie arc."),
('Сцена «Ральф приходит к Тони» (S04E09)','sopranos-ralph',
 "the cramped back office of a New Jersey strip club at night, empty.",
 "slightly high angle over the desk, 28mm lens",
 "in the foreground, a cluttered desk with an old black office telephone, an old adding machine whose short paper tape lies still, loose papers, a glass of whiskey and a glass ashtray with one lit cigarette. Behind: dark green walls with small pink diamond-shaped lights, a pool table with green felt under a glowing stained-glass window made of amber, green and red squares, and steel beer kegs stacked in the corner. No posters.",
 "one thin thread of smoke rises only from the tip of the cigarette; the pink diamond lights pulse slowly.",
 "the glowing stained glass, the pink lights and one desk lamp",
 "sickly green and amber with pink spill; grief, guilt and dirty money."),
('ГЛАВНЫЙ «Американский психопат»','film-psycho',
 "a white marble bathroom in a 1987 Manhattan luxury apartment, early morning, empty.",
 "symmetrical frontal shot, 50mm lens",
 "a wide mirror above a white marble sink with a chrome faucet; on the counter, a perfectly straight row of skincare bottles and jars, an open jar of white face-mask cream, a folded white towel, a chrome razor, and one bone-white business card leaning against the mirror. The mirror reflects only the white wall behind.",
 "a single water drop forms on the faucet and falls into the sink, again and again; a faint wisp of steam rises from the sink.",
 "cold white light from frosted glass fixtures",
 "icy white and chrome; sterile perfection hiding a cold emptiness."),
('Сцена «Патрик Бейтман приходит в офис»','american-psycho',
 "a 1987 Wall Street executive office in the morning, empty.",
 "three-quarter view from the doorway, 35mm lens",
 "grey-green walls with two small framed prints; in the center, a polished mahogany desk with a black leather office chair; on the desk, a sleek black telephone, a silver portable cassette player with headphones and a glass of sparkling water. Behind, tall windows with half-closed metal venetian blinds and Manhattan skyscrapers behind them.",
 "bubbles rise in the sparkling water; haze drifts slowly between the skyscrapers behind the blinds.",
 "cold morning daylight through the blinds",
 "cold grey-green and mahogany; sterile, arrogant 1980s yuppie morning."),
('Сцена «Визитки: чья круче»','american-psycho-cards',
 "a 1987 Wall Street boardroom, empty.",
 "low grazing angle across the table, 100mm macro lens, very shallow focus",
 "on a dark polished wooden table, five business cards laid in a neat row, each a slightly different shade of white (bone, eggshell, ivory), with tiny raised black lettering too small to read; beside them, a crystal tumbler of whiskey with ice. Behind, out of focus, dark wood paneling and venetian blinds.",
 "water droplets slide down the cold tumbler; a soft highlight glides slowly along the edge of the cards and back.",
 "soft daylight through the blinds in a dim room",
 "dark wood with creamy whites; petty envy, a man sweating over someone else's business card."),
('ГЛАВНЫЙ «Таксист»','film-taxi',
 "a wet 1970s New York side street at night, empty.",
 "low angle from the curb, 28mm lens",
 "in the center, a yellow 1970s Checker taxi cab with a checkered stripe parked at the curb with its roof light on; in front of it, a round manhole cover in the street. Behind, out of focus, shop windows glowing red and blue.",
 "white steam billows slowly only from the manhole and drifts past the taxi; neon reflections shimmer in the puddles.",
 "orange street lamps and red and blue neon reflected on the wet asphalt",
 "gritty 1970s, sodium orange; a lonely city at night."),
('Сцена «Одинокий человек Бога»','taxi-driver-lonely',
 "inside a 1970s New York yellow taxi cab at night, seen from the empty back seat.",
 "from the back seat, 28mm lens, looking forward through the windshield",
 "the scratched plexiglass partition, the empty driver's seat, an old mechanical taxi meter on the dashboard with no readable numbers; through the wet windshield, a blurry night street full of red, green and yellow neon signs with no readable letters.",
 "blurry neon lights slide slowly across the wet windshield; raindrops trickle down the glass.",
 "only the neon from outside",
 "red and green neon in darkness; insomnia, a lonely night shift in a filthy city."),
('Сцена «Трэвис зовёт Бетси на кофе»','taxi-driver-betsy',
 "a 1972 presidential campaign headquarters in New York on a sunny day, empty.",
 "eye level, 35mm lens",
 "red-white-and-blue paper bunting hanging along the walls; desks with typewriters, telephones and piles of leaflets; on the front desk, a small vase of yellow flowers and a paper cup of coffee; red carpet; big windows with daylight and green trees outside; flags with stars and stripes, no posters, no text.",
 "the bunting ripples gently in the breeze of a small desk fan; the desk fan blades turn.",
 "bright warm daylight from the windows",
 "warm red, white and blue, bright 1970s optimism; an awkward, hopeful invitation to a date."),
('ГЛАВНЫЙ «Бункер»','film-bunker',
 "a narrow underground concrete corridor of a Berlin bunker, April 1945, empty.",
 "one-point perspective down the corridor, 24mm lens, chest height",
 "bare light bulbs hanging from cables along the ceiling, a wooden chair and a small table with an old field telephone in the foreground, a heavy steel door half open on the side. No flags, symbols or insignia.",
 "the bulbs flicker and dim for a moment as distant explosions shake the bunker, then come back; fine dust drifts down from the ceiling.",
 "only the dim yellow bulbs",
 "grey-green concrete and sickly yellow; claustrophobic, the end is near."),
('Сцена «Приказ Штайнера»','downfall-bunker',
 "a small grey-green concrete conference room in a bunker, 1945, empty.",
 "high angle looking down at the table, 35mm lens",
 "a large old map of Europe on the wall; in the center, a big table covered with a paper map of Berlin with blue and red pencil marks; a pair of round wire-rimmed glasses lying on the map; a red-and-blue pencil thrown down across it; a green-shaded lamp hanging low above the table. No flags, symbols or insignia, no readable text.",
 "the hanging lamp sways gently back and forth, its pool of light sliding over the map and back; fine dust floats in the light.",
 "only the hanging lamp",
 "grey-green concrete and pale light; the seconds after a furious outburst, the war is lost."),
('ГЛАВНЫЙ «Титаник»','film-titanic',
 "the bow of a large 1912 ocean liner at sunset, empty deck.",
 "centered low angle looking forward to the tip of the bow, 24mm lens",
 "white railings converging to the point of the bow, wooden deck planks, a coiled rope and an anchor winch. Beyond the bow: calm open ocean and a golden-pink sunset sky.",
 "the sea glitters and slides past the bow as the ship moves forward; clouds drift slowly.",
 "warm low sun",
 "warm golden romance, epic and calm; the feeling of flying."),
('Сцена «Джек сажает Роуз в шлюпку»','titanic-boat',
 "the boat deck of a large 1912 ocean liner at night during the sinking, empty.",
 "eye level along the deck, 35mm lens",
 "white-painted steel walls with round brass deck lamps; in the center, an empty wooden lifeboat hanging from two steel davits by ropes beside the railing, the black ocean far below; a dropped white fur stole on the deck; an orange-and-white cork life jacket hanging on the railing.",
 "the empty lifeboat sways slightly on its ropes; the deck lamps flicker as the power fails.",
 "the round deck lamps, warm against the black night",
 "freezing blue night with warm failing lights; a tragic goodbye."),
('ГЛАВНЫЙ «Во все тяжкие»','film-bb',
 "the New Mexico desert at golden hour.",
 "low wide angle, 24mm lens",
 "in the center, an old 1980s white motorhome with faded brown stripes parked on the red sand, its side door open; a black pork-pie hat rests on the motorhome's metal step; a green gas mask lies on the sand nearby. Behind, red mesas under a huge sky.",
 "heat haze shimmers above the sand; small swirls of dust blow low across the ground.",
 "low warm sun",
 "sun-baked yellow-amber, high contrast; an ominous calm."),
('Сцена «Учитель химии едет на рейд» (S01E01)','breaking-bad-pilot',
 "inside a car on a DEA stakeout on a sunny Albuquerque suburban street, nobody inside.",
 "from the back seat between the front seats, 28mm lens, looking through the windshield",
 "on the dashboard, a pair of aviator sunglasses and a folded paper map; on the passenger seat, a black tactical vest with a gold badge patch and no text; a radio handset on a coiled cord. Through the windshield: a quiet street of beige stucco houses with garages, and blue mountains far away.",
 "heat haze shimmers above the asphalt; the radio's small red light blinks.",
 "harsh midday sun",
 "bleached sun with a yellow-green tint; a boring stakeout that is about to change a teacher's life."),
('Сцена «Уолт приходит к Гасу» (S02E11)','breaking-bad-gus',
 "an empty fast-food fried chicken restaurant in Albuquerque at night, closed.",
 "eye level, 28mm lens",
 "walls painted blue on the lower half and white above, red vinyl booths, light wooden tables and chairs, white floor tiles with small blue diamond inlays, ceiling fans, dark windows onto an empty parking lot. On the nearest table, a single paper cup of soda with a straw. No logos and no signs.",
 "the ceiling fans turn slowly; condensation drops slide down the cold soda cup.",
 "bright flat fluorescent ceiling light",
 "flat bright fluorescent; too clean, too polite, quietly menacing."),
('Сцена «Я тот, кто стучит» (S04E06 · S04E11)','breaking-bad-knocks',
 "a crawl space under a suburban house, seen from above.",
 "looking straight down through an open square wooden floor hatch, 24mm lens",
 "through the hatch: a dirt floor with bundles of cash wrapped in clear plastic stacked between wooden floor joists and pink insulation; one bare light bulb hanging on a cord.",
 "the bulb sways slowly on its cord and back, the shadows of the joists swing across the money; dust floats in the light.",
 "only the bare bulb",
 "harsh yellow and deep black; an obsession with money that has gone too far."),
('ГЛАВНЫЙ «Павел Дуров»','film-durov',
 "a minimalist dark office high above a glittering city at night, empty.",
 "centered shot toward a floor-to-ceiling window, 35mm lens",
 "in the foreground, a plain black desk with a single folded white paper airplane and a closed laptop. Behind the glass, the glittering night skyline of a big modern city.",
 "the city lights twinkle; tiny car lights stream along the highways far below.",
 "city lights and a faint cool desk light",
 "black, white and electric blue; minimal, calm freedom."),
('Сцена «Такер Карлсон · 2024»','durov-tucker',
 "a dark, elegant interview room, empty, just before filming.",
 "wide symmetrical shot, 35mm lens",
 "a wall of vertical dark wooden slats; dark marble shelves with a few white sculptural objects and a small white classical bust; in the center, two black armchairs facing each other with a small round black table between them holding two glasses of water; a window with light wooden blinds; two professional video cameras on tripods at the left and right edges, pointed at the chairs.",
 "the small red recording light on each camera blinks; light ripples faintly in the water glasses.",
 "warm low lamps and soft daylight through the blinds",
 "dark wood, black and white marble; serious, a big conversation is about to start."),
('ГЛАВНЫЙ «Clavicular»','film-clavicular',
 "a big podcast studio right after recording, empty.",
 "wide shot from a high corner, 24mm lens",
 "two large cream-colored sectional couches facing each other; between them a low wooden coffee table covered with snack boxes and sports-drink bottles; a wall of warm wooden planks with shelves of small trophies and boxes; a grey concrete wall wrapped with red, white and blue boxing-ring ropes; black podcast microphones on boom arms in front of the couches. No logos, no text.",
 "condensation drops slide down the cold bottles on the table; a tiny red recording light blinks on a camera at the edge of the frame.",
 "warm studio lights",
 "warm wood, cream and red-white-blue; loud, confident, a little bit show-off."),
('Сцена «Подкаст Impaulsive»','clavicular-impaulsive',
 "a podcast studio right after recording, empty, close-up on the guest's seat.",
 "eye level, 50mm lens, shallow focus",
 "the empty end of a cream-colored couch; a black podcast microphone on a boom arm pointing at the empty seat; a light-blue sports-drink bottle with no label standing on the couch armrest; behind, a grey concrete wall wrapped with red, white and blue boxing-ring ropes. No logos, no text.",
 "condensation drops slide down the cold bottle; dust specks drift slowly in the studio light.",
 "warm soft studio light",
 "cream, grey and red-white-blue; an honest, slightly awkward conversation just ended."),
]
def prompt(pl,cam,obj,mv,li,look):
    return (f"{HEAD} Place: {pl} Camera: {cam}, locked-off, does not move. Only these objects: {obj} "
            f"Moves (only this): {mv} Everything else stays perfectly still. Light: {li}, constant the whole time. "
            f"Mood: {look} {TAIL}")
if __name__=='__main__':
    o=['ФОНЫ — ПРОМТЫ ДЛЯ VEO / GEMINI','',
       'Настройки: 9:16, 8 с. Каждый блок — один промт, копируй целиком.',
       'Если всё равно вышла горизонталь — не страшно: всё важное в промтах по центру, я подрежу под телефон.',
       'Если «I can\'t generate that video» — убери из промта одну «острую» деталь (бумажный самолётик, свёрнутую купюру, сигарету) и прогони ещё раз.','','']
    for h,f,*x in P:o+=[f'=== {h} → файл {f}.mp4 ===','',prompt(*x),'','']
    open('фоны-промты-veo.txt','w').write('\n'.join(o));print(len(P))
