# Промты фонов под Veo / Gemini (13.0.2). Запуск из корня dota-: python3 tools/bg_veo.py → фоны-промты-veo.txt
# Учтено по тестам «Ральфа» (4 модели): чёрные полосы сверху/снизу (letterbox), рамка-плёнка с перфорацией,
# дым из ниоткуда, бумажная лента, которая растёт, лишние предметы (телефон, пачка), плакаты с буквами,
# «3D-рендер» вместо кино, свет, который меняется (петля не сходится), горизонталь вместо 9:16.
# Поэтому: всё важное — по центру (горизонталь можно подрезать), не больше 2–3 движений и только «текстурных»
# (дым из одной точки, пар, рябь, мерцание, покачивание туда-обратно), свет постоянный, список «только эти предметы».
HEAD="Vertical 9:16 full-frame phone video; the picture fills the whole frame from edge to edge."
TAIL=("Keep the main objects in the center of the frame. Objects never grow, change shape, appear or disappear; "
      "the last frame looks the same as the first. Photorealistic live-action footage with natural textures, not CGI, not a 3D render. "
      "Avoid: black bars, letterbox, frame borders, film strip, sprocket holes, split screen, text, letters, numbers, logos, watermarks, "
      "posters, signs, people, faces, hands, extra objects, extra smoke, camera movement, zoom, cuts.")
# (заголовок, файл, место, камера, только эти предметы, движение, свет, настроение)
P=[
('ГЛАВНЫЙ «Волк с Уолл-стрит»','film-wolf',
 "the trading floor of a 1990s Long Island brokerage firm at night, right after a wild office party, nobody left.",
 "low angle at desk height, 24mm lens, looking down a long aisle of identical desks",
 "in the center foreground, one desk with a beige push-button office telephone, its handset lying off the hook on the desk; next to it a thick stack of hundred-dollar bills with a rubber band, a gold Rolex wristwatch and a round glass fishbowl with one orange goldfish. Behind: rows of empty desks with boxy beige computer monitors glowing soft green with nothing on the screens; paper confetti on the carpet.",
 "the goldfish hovers in place, gently waving its fins; the green glow of the monitors flickers very slightly.",
 "one brass desk lamp on the foreground desk (warm gold) and cold green from the monitors",
 "saturated gold against money-green, glossy; the hangover after a party of young millionaires."),
('Сцена «Марк Ханна объясняет новичку правила Уолл-стрит»','wolf-of-wall-street',
 "a 1987 power-lunch restaurant on a high floor of a Manhattan skyscraper, midday, the dining room empty.",
 "eye level, 50mm lens, shallow focus, one table in the center",
 "on white linen, two full martini glasses with a green olive on a pick and three empty martini glasses pushed aside; a crystal ashtray with one lit cigarette resting in its notch; a gold lighter. Behind the table: a floor-to-ceiling window with a hazy late-1980s skyline.",
 "one thin thread of smoke rises only from the tip of the cigarette; haze drifts slowly over the city.",
 "soft daylight from the window and warm amber wall sconces",
 "rich amber inside, cool blue-grey city outside; a cynical lunch lesson about money."),
('Сцена «Швейцарский банк: Ça dépend»','wolf-swiss-bank',
 "a private banker's office in Geneva on a grey winter afternoon, polite, quiet and dangerous.",
 "symmetrical frontal shot, 35mm lens, a tall window in the center",
 "in the foreground, a polished walnut desk with a closed black leather folder, a thick stack of banknotes under a silver money clip, a silver fountain pen lying parallel to the folder and a small white espresso cup on a saucer. Through the window: Lake Geneva and the tall lake fountain shooting a white plume of water into the sky, snowy mountains far away.",
 "the fountain plume sways in the wind; a thin wisp of steam rises only from the espresso.",
 "soft cold daylight from the window and one brass desk lamp",
 "desaturated blue-grey with walnut and brass; discreet old money, everything has a price."),
('ГЛАВНЫЙ «Клан Сопрано»','film-sopranos',
 "dawn in the backyard of a large suburban New Jersey house.",
 "high three-quarter angle, 35mm lens",
 "in the center, a rectangular swimming pool with calm blue-green water and two wild mallard ducks floating on it. At the pool edge: one white lounge chair with a white terry bathrobe draped over it, a rolled newspaper in a plastic bag lying on the paving, and a small side table with an unlit half-smoked cigar in a glass ashtray. Behind: the back of the house with one lit kitchen window and tall trees.",
 "the ducks float almost in place, leaving small ripples; thin morning mist drifts low over the water.",
 "soft overcast dawn and a warm glow from the kitchen window",
 "muted greens and beige; the quiet melancholy of a man who has everything and still panics."),
('Сцена «Тони на первом приёме у психотерапевта» (S01E01)','sopranos-s01e01',
 "the waiting room of a psychiatrist's office in 1999, afternoon, empty.",
 "eye level, 50mm lens",
 "in the center foreground, a bronze sculpture of a reclining woman with smooth abstract forms on a white pedestal. Behind it, a half-open wooden door into the office, where two brown leather armchairs face each other with a box of tissues on a small table between them. A tall potted plant by the wall.",
 "dust specks float slowly in a sunbeam; the plant leaves barely stir.",
 "warm afternoon sun through wooden blinds laying still stripes of light on the floor",
 "warm beige and walnut; the nervous silence before a tough man's first therapy session."),
('Сцена «Тони у Мелфи: аттракционы и скука» (S06E09)','sopranos-s06e09',
 "an Italian-American church street festival in New Jersey at dusk, the street empty.",
 "slightly low angle, 85mm lens, background in soft bokeh",
 "in the center, a painted statue of a robed saint standing on a decorated wooden platform; long satin ribbons hang from its shoulders with dollar bills pinned along them. Above the street, strings of colored light bulbs. At the side, a closed food stand with a tray of powdered-sugar pastries. Far in the background, out of focus, a stopped spinning-teacup carnival ride.",
 "the ribbons with the pinned bills flutter in a light breeze; the bulbs twinkle softly.",
 "warm bulbs against a deep blue evening sky",
 "warm festive bokeh, nostalgic and a little sad: the fun is already over."),
('Сцена «Где моя арка?» (S01–S02)','sopranos-arc',
 "the apartment of a young New Jersey gangster who dreams of writing movies, at night, late 1990s.",
 "table height, 35mm lens",
 "in the center on a wooden table, an electric typewriter with a blank sheet of paper in it, a short stack of paper with no visible writing, a heavy glass ashtray with one lit cigarette, an open can of beer, and a stack of VHS tapes in plain black cases. Behind the table, against the wall, a glowing home aquarium with a few tropical fish.",
 "the fish drift slowly in the aquarium; one thin thread of smoke rises only from the tip of the cigarette.",
 "one warm desk lamp and the cold blue light of the aquarium",
 "cold blue and warm amber; a small-time gangster who wants his life to have a movie arc."),
('Сцена «Ральф приходит к Тони» (S04E09)','sopranos-ralph',
 "the small back office of a New Jersey strip club at night, empty.",
 "slightly high angle over the desk, 28mm lens",
 "in the center, a cluttered dark wooden desk with a thick brown paper envelope with banknotes sticking out, an old adding machine whose short paper tape lies still, a glass of whiskey and a glass ashtray with one lit cigarette. Behind: dark wood-paneled walls with nothing hanging on them, steel beer kegs stacked in the corner, and a small old television on a shelf showing a blurry horse race. At the side, a half-open door to the dark club glowing with pink light.",
 "the horse race flickers on the TV; the pink light through the door pulses slowly; one thin thread of smoke rises only from the tip of the cigarette.",
 "one green-shaded banker's lamp, pink neon through the door gap and the TV glow",
 "sickly green and tungsten with pink spill; grief, guilt and dirty money."),
('ГЛАВНЫЙ «Американский психопат»','film-psycho',
 "a white marble bathroom in a 1987 Manhattan luxury apartment, early morning, empty.",
 "symmetrical frontal shot, 50mm lens",
 "a wide mirror above a white marble sink with a chrome faucet; on the counter, a perfectly straight row of skincare bottles and jars, an open jar of white face-mask cream, a folded white towel, a chrome razor, and one bone-white business card leaning against the mirror. The mirror reflects only the white wall behind.",
 "a single water drop forms on the faucet and falls into the sink, again and again; a faint wisp of steam rises from the sink.",
 "cold white light from frosted glass fixtures",
 "icy white and chrome; sterile perfection hiding a cold emptiness."),
('Сцена «Патрик Бейтман приходит в офис»','american-psycho',
 "a minimalist 1987 Wall Street office, morning, empty.",
 "three-quarter view from above a glass desk, 35mm lens",
 "on the glass desk, a silver portable cassette player with orange foam headphones, a tall glass of sparkling mineral water with a lime slice, an open black leather planner with blank pages and a fountain pen. Behind: tall windows with half-open metal blinds onto hazy office towers.",
 "bubbles rise in the sparkling water; haze drifts slowly between the towers.",
 "cold morning daylight through the blinds, the striped shadows on the desk stay still",
 "steel blue and white; an arrogant, polished 1980s yuppie morning."),
('Сцена «Визитки: чья круче»','american-psycho-cards',
 "a dark glossy boardroom table in 1987.",
 "low grazing angle, 100mm macro lens, very shallow focus",
 "in the center, five business cards laid in a neat fan, each a slightly different shade of white (bone, eggshell, ivory), with tiny raised embossed lines too small to read; beside them, a crystal tumbler of whiskey with ice.",
 "water droplets slide down the cold tumbler; a soft highlight glides slowly along the edge of the top card and back.",
 "one narrow soft spotlight from above in a dark room",
 "near-black with creamy whites; petty envy, a man sweating over someone else's business card."),
('ГЛАВНЫЙ «Таксист»','film-taxi',
 "a wet 1970s New York side street at night, empty.",
 "low angle from the curb, 28mm lens",
 "in the center, a yellow 1970s Checker taxi cab parked at the curb with its roof light on; in front of it, a round manhole cover in the street. Behind, out of focus, shop windows glowing red and blue.",
 "white steam billows slowly only from the manhole and drifts past the taxi; neon reflections shimmer in the puddles.",
 "orange street lamps and red and blue neon reflected on the wet asphalt",
 "gritty 1970s, sodium orange; a lonely city at night."),
('Сцена «Одинокий человек Бога»','taxi-driver-lonely',
 "a tiny cheap rented room in 1970s New York at night.",
 "table height, 35mm lens",
 "in the center on a small wooden table, an open diary with blurred handwriting and no readable words, a pen, a bottle of brandy, and a glass of water with a fizzing tablet dissolving in it. An olive-green army field jacket hangs on the back of the chair. Behind: an old portable television showing grey static and a window with cheap blinds.",
 "bubbles rise from the fizzing tablet in the glass; the TV static flickers.",
 "one bare ceiling bulb, steady red neon from the street through the blinds and the TV glow",
 "nicotine yellow and red; insomnia and isolation."),
('Сцена «Трэвис зовёт Бетси на кофе»','taxi-driver-betsy',
 "a 1970s New York coffee shop booth by the window on a rainy evening, empty.",
 "eye level across the table, 50mm lens",
 "on a formica table in the center, two white mugs of hot black coffee, one slice of apple pie on a small plate with a fork, a chrome napkin holder, a glass sugar pourer and a round red-white-and-blue campaign button with stars and no text. Red vinyl booth seats. Behind: a rain-streaked window with blurred street lights and a parked yellow taxi.",
 "steam rises from both coffee mugs; raindrops slide down the window.",
 "warm diner ceiling lights inside and cool blue light outside",
 "warm gold inside, blue rain outside; an awkward, hopeful first date."),
('ГЛАВНЫЙ «Бункер»','film-bunker',
 "a narrow underground concrete corridor of a Berlin bunker, April 1945, empty.",
 "one-point perspective down the corridor, 24mm lens, chest height",
 "bare light bulbs hanging from cables along the ceiling, a wooden chair and a small table with an old field telephone in the foreground, a heavy steel door half open on the side. No flags, symbols or insignia.",
 "the bulbs flicker and dim for a moment as distant explosions shake the bunker, then come back; fine dust drifts down from the ceiling.",
 "only the dim yellow bulbs",
 "grey-green concrete and sickly yellow; claustrophobic, the end is near."),
('Сцена «Приказ Штайнера»','downfall-bunker',
 "a concrete bunker meeting room, 1945, empty.",
 "high angle looking down at a table, 35mm lens",
 "on a large wooden table, a big paper city map with blurred streets and red and blue pencil arrows, a pair of round wire-rimmed glasses lying on the map, a red pencil broken in two and a few colored pencils. A green-shaded lamp hangs low above the table on a cord. No flags, symbols or insignia, no readable text.",
 "the hanging lamp sways gently back and forth, its pool of light sliding over the map and back; fine dust floats in the light.",
 "only the hanging lamp",
 "grey concrete and greenish light; the seconds after a furious outburst, the war is lost."),
('ГЛАВНЫЙ «Титаник»','film-titanic',
 "the bow of a large 1912 ocean liner at sunset, empty deck.",
 "centered low angle looking forward to the tip of the bow, 24mm lens",
 "white railings converging to the point of the bow, wooden deck planks, a coiled rope and an anchor winch. Beyond the bow: calm open ocean and a golden-pink sunset sky.",
 "the sea glitters and slides past the bow as the ship moves forward; clouds drift slowly.",
 "warm low sun",
 "warm golden romance, epic and calm; the feeling of flying."),
('Сцена «Джек сажает Роуз в шлюпку»','titanic-boat',
 "the side deck of a large 1912 ocean liner at night during the sinking, empty.",
 "eye level along the deck, 35mm lens",
 "in the center, an empty wooden lifeboat hanging from two steel davits by ropes beside the railing, the black ocean far below. On the deck near the railing, a dropped white fur stole; an orange-and-white cork life jacket hangs on the railing.",
 "the empty lifeboat sways slightly on its ropes; the deck lamps flicker as the power fails.",
 "the ship's deck lamps and lit portholes, warm against the black night",
 "freezing blue night with warm failing lights; a tragic goodbye."),
('ГЛАВНЫЙ «Во все тяжкие»','film-bb',
 "the New Mexico desert at golden hour.",
 "low angle, 35mm lens",
 "in the center foreground, a black pork-pie hat resting on top of a weathered wooden fence post. Behind it, an empty straight two-lane highway leading to red mesas under a huge sky.",
 "heat haze shimmers above the asphalt; dry grass sways in the wind.",
 "low warm sun",
 "sun-baked yellow-amber, high contrast; an ominous calm."),
('Сцена «Учитель химии едет на рейд» (S01E01)','breaking-bad-pilot',
 "the New Mexico desert at midday, nobody around.",
 "wide shot, 24mm lens, low horizon, big blue sky",
 "in the center, an old 1980s white motorhome with faded brown stripes parked on the sand, its side door open; a green gas mask lies on the sand by the door; a pair of khaki pants is caught on a nearby desert shrub.",
 "the khaki pants flap on the shrub in the hot wind; small swirls of dust blow low across the sand.",
 "harsh overhead sun",
 "bleached sun with a yellow-green tint; absurd and dangerous."),
('Сцена «Уолт приходит к Гасу» (S02E11)','breaking-bad-gus',
 "an empty fast-food fried chicken restaurant in Albuquerque at night, closed.",
 "eye level into a booth, 35mm lens",
 "on the table of a yellow booth, a red plastic tray with a paper cup of soda with a straw and a basket of golden fried chicken. Clean tiled floor, big windows onto a dark empty parking lot. No logos and no signs.",
 "condensation drops slide down the cold soda cup; one fluorescent tube flickers very slightly.",
 "bright flat fluorescent ceiling light",
 "flat yellow fluorescent; too clean, too polite, quietly menacing."),
('Сцена «Я тот, кто стучит» (S04E06 · S04E11)','breaking-bad-knocks',
 "a crawl space under a suburban house.",
 "low angle at ground level, 24mm lens",
 "in the center, bundles of cash wrapped in clear plastic stacked on the dirt floor between wooden floor joists and pink insulation; one bare light bulb hangs on a cord above them.",
 "the bulb sways slowly on its cord and back, the shadows of the joists swing across the money; dust floats in the light.",
 "only the bare bulb",
 "harsh yellow and deep black; an obsession with money that has gone too far."),
('ГЛАВНЫЙ «Павел Дуров»','film-durov',
 "a minimalist dark penthouse office high above Dubai at night, empty.",
 "centered shot toward a floor-to-ceiling window, 35mm lens",
 "in the foreground, a plain black desk with a single folded white paper airplane and a closed laptop. Behind the glass, the glittering night skyline of Dubai.",
 "the city lights twinkle; tiny car lights stream along the highways far below.",
 "city lights and a faint cool desk light",
 "black, white and electric blue; minimal, calm freedom."),
('Сцена «Такер Карлсон · 2024»','durov-tucker',
 "an interview room in Dubai at blue hour, empty, just before filming.",
 "wide symmetrical shot, 35mm lens",
 "two dark leather armchairs facing each other with a small round table between them holding two glasses of water; two professional video cameras on tripods at the left and right edges, pointed at the chairs. Behind, a tall window with the Dubai skyline.",
 "the small red recording light on each camera blinks; the city lights twinkle.",
 "warm table lamps inside and deep blue dusk outside",
 "warm amber and deep blue; serious, a big conversation is about to start."),
('ГЛАВНЫЙ «Clavicular»','film-clavicular',
 "a city street at night after rain, an outdoor café table.",
 "close shot at table height, 35mm lens",
 "in the center on the table, a smartphone standing on a small tripod with a small ring light next to it, and a small round hand mirror lying flat; the phone screen shows a live stream made of colorful chat bubbles and hearts with no letters. Behind, blurred neon shop lights and wet pavement.",
 "chat bubbles and hearts float up the phone screen; neon reflections ripple on the wet pavement.",
 "the ring light and neon reflections",
 "purple, pink and cyan neon; loud, confident nightlife."),
('Сцена «Подкаст Impaulsive»','clavicular-impaulsive',
 "a podcast studio right after recording, empty.",
 "slightly high angle over the table, 28mm lens",
 "on a wooden table in the center, three podcast microphones on boom arms, a few plain energy-drink cans, and a smartphone lying face up with a green message bubble on its screen. Behind, a wall of wooden planks with neon light strips and a white couch.",
 "the neon strips slowly breathe brighter and dimmer; condensation drops slide down a cold can.",
 "warm studio lights with pink and cyan neon",
 "playful warm light with neon accents; a loud, honest conversation just ended."),
]
def prompt(pl,cam,obj,mv,li,look):
    return (f"{HEAD} Place: {pl} Camera: {cam}, locked-off, does not move. Only these objects: {obj} "
            f"Moves (only this): {mv} Everything else stays perfectly still. Light: {li}, constant the whole time. "
            f"Mood: {look} {TAIL}")
if __name__=='__main__':
    o=['ФОНЫ — ПРОМТЫ ДЛЯ VEO / GEMINI','',
       'Настройки: 9:16, 8 с. Каждый блок — один промт, копируй целиком.',
       'Если всё равно вышла горизонталь — не страшно: всё важное в промтах по центру, я подрежу под телефон.','','']
    for h,f,*x in P:o+=[f'=== {h} → файл {f}.mp4 ===','',prompt(*x),'','']
    open('фоны-промты-veo.txt','w').write('\n'.join(o));print(len(P))
